# Default values for citizen-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param enabled Set to false to disabling rending templates in this chart. Used to dispable rendering this chart when developing other sub-charts.
enabled: true

## @param replicaCount Number of replicas
##
replicaCount: 1

image:
  registry: image-registry.openshift-image-registry.svc:5000
  repository: 0198bb-tools/citizen-api
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

## @param nameOverride String to partially override citizen-api.fullname template (will maintain the release name)
##
nameOverride: ""

## @param fullnameOverride String to fully override citizen-api.fullname template
##
fullnameOverride: ""

serviceAccount:
  # The name of the service account to use, defaults to "default"
  name: ""

## @param podAnnotations Annotations for pods.
##
podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

## Autoscaling configuration
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
## @param autoscaling.enabled Enable Horizontal POD autoscaling
## @param autoscaling.minReplicas Minimum number of replicas
## @param autoscaling.maxReplicas Maximum number of replicas
## @param autoscaling.targetCPUUtilizationPercentage Target CPU utilization percentage
## @param autoscaling.targetMemoryUtilizationPercentage Target Memory utilization percentage
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## @param nodeSelector Node labels for pods assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## @param tolerations Tolerations for pods assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## @param Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## @param enable prom scrape metrics
##
## if you enable metrics be sure to add these podAnnotations
##
##     podAnnotations:
##       prometheus.io/scrape: 'true'
##       prometheus.io/port: "52325"    
metrics:
  enabled: false

## @param formRecognizer
## Todo: move formRecognizer.apiKey to secret
##
formRecognizer:
  endpoint: ""
  apiKey: ""
  model: ""

## @param
## Todo: move rabbitmq.password to secret
##
rabbitmq:
  host: rabbitmq
  port: "5672"
  username: guest
  password: guest

redis:
  connectionString: ""

  host: ""
  port: 6379

  ## @param redis.sentinel.enabled Use Redis Sentinel.
  ## @param redis.sentinel.serviceName .
  sentinel:
    enabled: false
    serviceName: ""

## @param
## objectStorage.accessKey The username used to access the bucket
## objectStorage.secretKey The password used to access the bucket
objectStorage:
  accessKey: ""
  bucketName: ""
  endpoint: ""
  secretKey: ""

## @param
##
splunk:
  enabled: false
  endpoint:
  token:

## @param
##
jaeger:
  enabled: false
  exporter:
    endpoint: http://jaeger-collector:14268/api/traces
    protocol: "http/thrift.binary"

swagger:
  enabled: false

vault:
  enabled: false
