apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "staff-web.configmapName" . }}
  labels: {{- include "staff-web.labels" . | nindent 4 }}
data:
  keycloak.config.json: |-
{{ include "staff-web.tplvalues.render" ( dict "value" .Values.keycloakConfig "context" $ ) | indent 4 }}
  nginx-api-proxy-pass.conf: |-
    location /api {
      resolver kube-dns.kube-system.svc.cluster.local;
      proxy_pass http://{{ .Release.Name }}-staff-api.{{ .Values.global.namespace }}.svc.cluster.local:8080/api;
      client_max_body_size 10M;
    }
    error_log stderr warn;
