apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: citizen-api
  labels:
    app: citizen-api
    app.kubernetes.io/name: citizen-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: citizen-api
    app.kubernetes.io/part-of: traffic-court
spec:
  completionDeadlineSeconds: 1200
  replicas: 1
  selector:
    name: citizen-api
  strategy:
    type: Rolling
    maxSurge: 50%
    maxUnavailable: 0
  template:
    metadata:
      labels:
        dev-app: traffic-court
        name: citizen-api
    spec:
      containers:
        - image: >-
            image-registry.openshift-image-registry.svc:5000/0198bb-tools/dispute-api:dev
          name: citizen-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TicketSearchApi__BaseUrl
              value: "http://ticket-search/"
            - name: Serilog__MinimumLevel
              value: Debug
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
            livenessProbe:
              httpGet:
                path: "/health"
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              timeoutSeconds: 60
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: "/health"
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 10
              timeoutSeconds: 60
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
          #volumeMounts:
          #- name: configuration-volume
          #mountPath: /usr/share/nginx/html/assets/app.config.json
          #subPath: app.config.json
      #volumes:
      #- name: configuration-volume
      #configMap:
      #name: citizen-web-configuration
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - citizen-api
        from:
          kind: ImageStreamTag
          namespace: "0198bb-tools"
          name: "citizen-api:dev"
status: {}
