# Default values for staff-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param replicaCount Number of replicas
##
replicaCount: 1

image:
  registry: image-registry.openshift-image-registry.svc:5000
  repository: 0198bb-tools/staff-web
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

## @param nameOverride String to partially override staff-web.fullname template (will maintain the release name)
##
nameOverride: ""

## @param fullnameOverride String to fully override staff-web.fullname template
##
fullnameOverride: ""

resources:
  limits:
    cpu: 150m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

## @param route.allowedIPs List of space separated IP addresses that can connect to this route
route:
  allowedIPs: ""

## Autoscaling configuration
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
## @param autoscaling.enabled Enable Horizontal POD autoscaling
## @param autoscaling.minReplicas Minimum number of replicas
## @param autoscaling.maxReplicas Maximum number of replicas
## @param autoscaling.targetCPUUtilizationPercentage Target CPU utilization percentage
## @param autoscaling.targetMemoryUtilizationPercentage Target Memory utilization percentage
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


## @param appConfig application configuration json file
## appConfig: |-
##    {
##      "production": false,
##      "environment": "Dev",
##      "version": "2.0.2",
##      "useMockServices": false,
##      "apiBaseUrl": "/api",
##      "features": {
##        "dispute":true
##      }
##    }
appConfig: ""

## @param keycloakConfig keycloak configuration file
## keycloakConfig: |-
##    {
##      "config": {
##        "url": "https://oidc-0198bb-dev.apps.silver.devops.gov.bc.ca",
##        "realm": "traffic-court",
##        "clientId": "staff-portal"
##      },
##      "initOptions": {
##        "onLoad": "check-sso",
##        "silentCheckSsoRedirectUri": "/assets/silent-check-sso.html"
##      }
##    }
##
keycloakConfig: ""


## Pod Disruption Budget configuration
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
##
pdb:
  ## @param pdb.create Enable/disable a Pod Disruption Budget creation
  ##
  create: false
  ## @param pdb.minAvailable Minimum number/percentage of pods that should remain scheduled
  ##
  minAvailable: 1
  ## @param pdb.maxUnavailable Maximum number/percentage of pods that may be made unavailable
  ##
  maxUnavailable: ""
