apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "citizen-web.configmapName" . }}
  labels: {{- include "citizen-web.labels" . | nindent 4 }}
data:
{{- if and .Values.appConfig (not .Values.existingAppConfigConfigmap) }}
  app.config.json: |-
{{ include "citizen-web.tplvalues.render" ( dict "value" .Values.appConfig "context" $ ) | indent 4 }}
{{- end }}
  nginx-api-proxy-pass.conf: |-
    location /api {
      resolver kube-dns.kube-system.svc.cluster.local;
      proxy_pass http://{{ .Release.Name }}-citizen-api.{{ .Values.global.namespace }}.svc.cluster.local:8080/api;
      client_max_body_size 10M;
    }
    error_log stderr warn;
