# Default values for form-recognizer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: ""
nameOverride: ""

api:
  replicaCount: 1

  image:
    repository: mcr.microsoft.com/azure-cognitive-services/form-recognizer/custom-api
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2.1-preview"

layout:
  replicaCount: 1

  image:
    repository: image-registry.openshift-image-registry.svc:5000/0198bb-tools/form-recognizer-layout
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2.1-preview"

  containerSecurityContext:
    enabled: true
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true

proxy:
  replicaCount: 1

  image:
    repository: docker.io/nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "stable-alpine"

supervised:
  replicaCount: 1

  image:
    repository: mcr.microsoft.com/azure-cognitive-services/form-recognizer/custom-supervised
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2.1-preview"

podSecurityContext:
  enabled: false

storage:
  logs:
    size: 500Mi
    storageClassName: ~
  shared:
    size: 1Gi
    storageClassName: ~

rabbitmq:
  secret:
    name: rabbitmq
    passwordKey: rabbitmq-password
  username: user
  host: rabbitmq
  port: 5672
  virtualHost: ocr

azure:
  apiKey:
    secret:
      key: FORMRECOGNIZER__APIKEY
  billing:
    endpoint: https://ag-ocrformrecognizer-dev.cognitiveservices.azure.com/

imagePullSecrets: []

podAnnotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
