# Default values for oracle-data-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param replicaCount Number of replicas
##
replicaCount: 1

image:
  registry: image-registry.openshift-image-registry.svc:5000
  repository: 0198bb-tools/oracle-data-api
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

## @param nameOverride String to partially override oracle-data-api.fullname template (will maintain the release name)
##
nameOverride: ""

## @param fullnameOverride String to fully override oracle-data-api.fullname template
##
fullnameOverride: ""

serviceAccount:
  # The name of the service account to use, defaults to "0198bb-vault"
  name: "0198bb-vault"

resources:
  limits:
    cpu: 250m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 768Mi

## Autoscaling configuration
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
## @param autoscaling.enabled Enable Horizontal POD autoscaling
## @param autoscaling.minReplicas Minimum number of replicas
## @param autoscaling.maxReplicas Maximum number of replicas
## @param autoscaling.targetCPUUtilizationPercentage Target CPU utilization percentage
## @param autoscaling.targetMemoryUtilizationPercentage Target Memory utilization percentage
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

