apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata: 
  creationTimestamp: null  
  name: dispute-api
spec:
  selector:
    app: dispute-api
  replicas: 1  
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: dispute-api
      creationTimestamp: null     
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: SPLUNK_COLLECTOR_URL
          value: ""
        - name: SPLUNK_TOKEN
          value: ""
        image: ' '
        name: dispute-api
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - dispute-api
      from:
        kind: ImageStreamTag
        namespace: 0198bb-tools
        name: dispute-api:latest
    type: ImageChange
status: {}
