# global values
global:
  licenseplate: 0198bb
  namespace:
  vault:
    # licenseplate-nonprod or licenseplate-prod
    role: ''
    # 'dev/', 'test/' or ''
    path: ''
  env:

arc-dispute-api:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: 0198bb-tools/arc-dispute-api
    tag: ""
    pullPolicy: IfNotPresent
  env:
    "ASPNETCORE_ENVIRONMENT": "Production"
    "ASPNETCORE_URLS": "http://*:8080"
    "OTEL_EXPORTER_JAEGER_ENDPOINT": "http://jaeger-collector:14268/api/traces"
    "OTEL_EXPORTER_JAEGER_PROTOCOL": "http/thrift.binary"
    "Serilog__Using__0": "Serilog.Sinks.Splunk"
    "Serilog__Using__1": "Serilog.Sinks.Console"
    "Serilog__WriteTo__0__Name": "EventCollector"
    "Serilog__WriteTo__1__Name": "Console"
    "Serilog__WriteTo__1__Args__theme": "Serilog.Sinks.SystemConsole.Themes.ConsoleTheme::None, Serilog.Sinks.Console"
    "Serilog__WriteTo__1__Args__outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"

citizen-api:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: 0198bb-tools/citizen-api
    tag: ""
    pullPolicy: IfNotPresent
  env:
    "ASPNETCORE_ENVIRONMENT": "Production"
    "ASPNETCORE_URLS": "http://*:8080"
    "OTEL_EXPORTER_JAEGER_ENDPOINT": "http://jaeger-collector:14268/api/traces"
    "OTEL_EXPORTER_JAEGER_PROTOCOL": "http/thrift.binary"
    "RabbitMq__Host": "rabbitmq"
    "Serilog__Using__0": "Serilog.Sinks.Splunk"
    "Serilog__Using__1": "Serilog.Sinks.Console"
    "Serilog__WriteTo__0__Name": "EventCollector"
    "Serilog__WriteTo__1__Name": "Console"
    "Serilog__WriteTo__1__Args__theme": "Serilog.Sinks.SystemConsole.Themes.ConsoleTheme::None, Serilog.Sinks.Console"
    "Serilog__WriteTo__1__Args__outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"

citizen-web:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: 0198bb-tools/citizen-web
    tag: ""
    pullPolicy: IfNotPresent

oracle-data-api:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: 0198bb-tools/oracle-data-api
    tag: ""
    pullPolicy: IfNotPresent
  env:
    "CODETABLE_REFRESH_CRON": "0 0 * * * *"
    "CODETABLE_REFRESH_ENABLED": "true"
    "H2_DATASOURCE": "jdbc:h2:file:/data/h2"
    "OTEL_EXPORTER_JAEGER_ENDPOINT": "http://jaeger-collector:14250"
    "REDIS_HOST": "redis-master"
    "REDIS_PORT": "6379"
    "UNASSIGN_DISPUTES_CRON": "0 0/5 * * * *"
    "UNASSIGN_DISPUTES_ENABLED": "true"
    "ORDS_API_URL": "https://dev.jag.gov.bc.ca/ords/devj/occamords/occam/v1"
    "ORDS_API_TIMEOUT": "2000"
    "ORDS_API_RETRY_COUNT": "3"
    "ORDS_API_RETRY_DELAY": "5"

staff-api:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: 0198bb-tools/staff-api
    tag: ""
    pullPolicy: IfNotPresent
  env:
    "ASPNETCORE_ENVIRONMENT": "Production"
    "ASPNETCORE_URLS": "http://*:8080"
    "OTEL_EXPORTER_JAEGER_ENDPOINT": "http://jaeger-collector:14268/api/traces"
    "OTEL_EXPORTER_JAEGER_PROTOCOL": "http/thrift.binary"
    "RabbitMq__Host": "rabbitmq"
    "Serilog__Using__0": "Serilog.Sinks.Splunk"
    "Serilog__Using__1": "Serilog.Sinks.Console"
    "Serilog__WriteTo__0__Name": "EventCollector"
    "Serilog__WriteTo__1__Name": "Console"
    "Serilog__WriteTo__1__Args__theme": "Serilog.Sinks.SystemConsole.Themes.ConsoleTheme::None, Serilog.Sinks.Console"
    "Serilog__WriteTo__1__Args__outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"

staff-web:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: 0198bb-tools/staff-web
    tag: ""
    pullPolicy: IfNotPresent

workflow-service:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: 0198bb-tools/workflow-service
    tag: ""
    pullPolicy: IfNotPresent
  env:
    "ASPNETCORE_ENVIRONMENT": "Production"
    "ASPNETCORE_URLS": "http://*:8080"
    "OTEL_EXPORTER_JAEGER_ENDPOINT": "http://jaeger-collector:14268/api/traces"
    "OTEL_EXPORTER_JAEGER_PROTOCOL": "http/thrift.binary"
    "RabbitMq__Host": "rabbitmq"
    "Serilog__Using__0": "Serilog.Sinks.Splunk"
    "Serilog__Using__1": "Serilog.Sinks.Console"
    "Serilog__WriteTo__0__Name": "EventCollector"
    "Serilog__WriteTo__1__Name": "Console"
    "Serilog__WriteTo__1__Args__theme": "Serilog.Sinks.SystemConsole.Themes.ConsoleTheme::None, Serilog.Sinks.Console"
    "Serilog__WriteTo__1__Args__outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
