name: Prod-Cucumber Tests

on:
  push:
    branches: [prod]
  workflow_dispatch:

jobs:
  cucumber-tests:
    name: Runs cucumber-tests
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Pull Git repo
        uses: actions/checkout@v2

      - name: Login to RedHat Container Repo
        id: build-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |          
          docker login ${{ secrets.REDHAT_REPO }} -u ${{ secrets.REDHAT_REPO_USER }} -p ${{ secrets.REDHAT_REPO_AUTH }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Node / Npm
        uses: actions/setup-node@v2
        with:
          node-version: '14.15'

      - name: Run Frontend UI
        run: |
          cd src/frontend/citizen-portal
          sudo npm install
          sudo npm install -g @angular/cli
          ng serve &

      - name: Run Backend API
        run: |
          cd ${{ github.workspace }}/src/backend/TrafficCourtsApi
          docker build -f Dockerfile -t disputev1 .
          docker run -p 8080:8080 -d disputev1

      - name: Maven requires chrome driver
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Running UI and API Tests
        run: |
          cd ${{ github.workspace }}
          mvn verify -f tests/pom.xml -e

      # Upload Spark report for debugging purposes
      - name: Upload Spark report for debugging purposes
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-spark-report
          path: ./tests/test-output/extent/Spark/Index.html

      # Upload Cucumber JSON for debugging purposes
      - name: Upload Cucumber JSON for debugging purposes
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-json-report
          path: ./tests/target/cucumber-reports/CucumberTestReport.json
